### ISSUE TITLE
Better document in add_beam & add_joint docstrings what they do to avoid confusion with add_part and add_connection

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#113]
Following this discussion: https://github.com/gramaziokohler/compas_timber/pull/98#issuecomment-1542231445

We might want to consider changing the relationship between `TimberAssembly` and `Assembly` to composition rather than inheritance.

**Comment by chenkasirer** [comment]
Another thing to try:
- overwrite (or append) to `Assembly.add_part.__doc__`

**Comment by obucklin** [comment]
This is outdated due to change to compas_model
