### ISSUE TITLE
Beam/Brep.trim doesn't cap ends

### ISSUE THREAD

**Issue by obucklin** [gramaziokohler/compas_timber#173]

**Comment by chenkasirer** [comment]
Hey @obucklin `Brep.trim` should cap planar holes by default. Can you please provide a minimal example where you see the issue so that I can look into it?

**Comment by chenkasirer** [comment]
Update: I can reproduce this, it is a bug in compas core, most likely introduced after the latest rework of `RhinoBrep` in compas 2.0. Will make a fix ASAP.
