### ISSUE TITLE
TimberAssembly GH Component rework

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#216]
- describe the intended rule mechanism using Miro diagram / pseudo code
- rework the copying/referencing mechanism of beams (maybe no copy, just reset method?) - done

**Comment by obucklin** [comment]
I still want to rework the components to have (at least the option to) trigger a recalc, instead of create geometry true/false. These should be considered together

**Comment by obucklin** [comment]
This may want to get upstreamed to CT core for reusability in other environments
