### ISSUE TITLE
remove show beam GH component

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#217]
@obucklin @jonashaldemann I see this has been removed already. Can we rename this card to something like "old component clean up" and we sit together for half an hour and remove old components? Cause I feel there might be a couple others we can remove

**Comment by jonashaldemann** [comment]
yes, let's to that and sit together

**Comment by obucklin** [comment]
Fo sho On 12. Feb 2024, at 16:24, jonashaldemann ***@***.***> wrote:﻿
yes, let's to that and sit together
