### ISSUE TITLE
surface to assembly

### ISSUE THREAD

**Issue by obucklin** [gramaziokohler/compas_timber#224]

**Comment by chenkasirer** [comment]
@mhelmrei check this out

**Comment by mhelmrei** [comment]
@chenkasirer which branch to check out?

**Comment by chenkasirer** [comment]
> @chenkasirer which branch to check out?

https://github.com/gramaziokohler/compas_timber/pull/236

@obucklin can you please provide instructions how to test? thanks!

**Comment by obucklin** [comment]
https://youtu.be/D9BZ9zfvSbw

**Comment by obucklin** [comment]
clone the branch, build the components, have fun!
