### ISSUE TITLE
Upstream Tbutt Joint

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#259]
Upstream (parts or whole) of the Tbutt joint from: https://github.com/MAS-dfab/compas_timber/blob/main/src/compas_timber/connections/t_butt.py

**Comment by chenkasirer** [comment]
@kangoananya  will find out who/when/what and @chenkasirer will supervise

**Comment by obucklin** [comment]
Is this stuff like dovetail, mortise+tenon, step joint?

**Comment by chenkasirer** [comment]
@papachap could you have a look and note here if there's anything that still needs to be done here?

**Comment by papachap** [comment]
closes https://github.com/gramaziokohler/compas_timber/pull/322
