### ISSUE TITLE
Feature system requirements

### ISSUE THREAD

**Issue by chenkasirer** [gramaziokohler/compas_timber#96]
Come up with some way to demonstrate a "live" TA flow.
- pure python
- compas_view

Original discussion on: https://github.com/gramaziokohler/compas_timber/pull/74

**Comment by obucklin** [comment]
@chenkasirer archive?

**Comment by chenkasirer** [comment]
I'm closing because this was addressed and somewhat simplified with the new Model and feature system by:
1. making features forward-only, but cached
2. adding cache invalidating decorator `reset_computed` to feature related methods
